services:
  nas:
    image: filebrowser/filebrowser:latest
    container_name: nas-server
    ports:
      - "8085:80"
    volumes:
      - ./shared-storage:/srv
      - ./app-data/database:/database
      - ./app-data/config:/config
    restart: unless-stopped